-- MySQL Script generated by MySQL Workbench
-- Fri Feb 14 13:31:42 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema AttendenceMadeEasy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `AttendenceMadeEasy` ;

-- -----------------------------------------------------
-- Schema AttendenceMadeEasy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `AttendenceMadeEasy` DEFAULT CHARACTER SET utf8 ;
USE `AttendenceMadeEasy` ;

-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`Student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`Student` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`Student` (
  `idstudent` INT NOT NULL,
  PRIMARY KEY (`idstudent`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`Student_has_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`Student_has_classes` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`Student_has_classes` (
  `Student_idstudent` INT NOT NULL,
  `classes_idclasses` INT NOT NULL,
  `classes_teacher_idteacher` INT NOT NULL,
  PRIMARY KEY (`Student_idstudent`, `classes_idclasses`, `classes_teacher_idteacher`),
  INDEX `fk_Student_has_classes_classes1_idx` (`classes_idclasses` ASC, `classes_teacher_idteacher` ASC) VISIBLE,
  INDEX `fk_Student_has_classes_Student1_idx` (`Student_idstudent` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`classes` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`classes` (
  `idclasses` INT NOT NULL,
  `teacher_idteacher` INT NOT NULL,
  `location` VARCHAR(255) NULL,
  `className` VARCHAR(45) NULL,
  `classTime` TIME NULL,
  `classescol` VARCHAR(45) NULL,
  PRIMARY KEY (`idclasses`, `teacher_idteacher`),
  INDEX `fk_classes_teacher1_idx` (`teacher_idteacher` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`teacher` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`teacher` (
  `idteacher` INT NOT NULL,
  PRIMARY KEY (`idteacher`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`user` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`user` (
  `iduser` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `Student_idstudent` INT NOT NULL,
  `teacher_idteacher` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_Student_idx` (`Student_idstudent` ASC) VISIBLE,
  INDEX `fk_user_teacher1_idx` (`teacher_idteacher` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `AttendenceMadeEasy`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `AttendenceMadeEasy`.`user` ;

CREATE TABLE IF NOT EXISTS `AttendenceMadeEasy`.`user` (
  `iduser` INT NOT NULL,
  `fname` VARCHAR(45) NULL,
  `lname` VARCHAR(45) NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` VARCHAR(45) NOT NULL,
  `Student_idstudent` INT NOT NULL,
  `teacher_idteacher` INT NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`iduser`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_user_Student_idx` (`Student_idstudent` ASC) VISIBLE,
  INDEX `fk_user_teacher1_idx` (`teacher_idteacher` ASC) VISIBLE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
