-- MySQL Script generated by MySQL Workbench
-- Fri Mar 20 10:14:05 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema attendencemadeeasy
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `attendencemadeeasy` ;

-- -----------------------------------------------------
-- Schema attendencemadeeasy
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `attendencemadeeasy` DEFAULT CHARACTER SET utf8 ;
USE `attendencemadeeasy` ;

-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`teacher`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`teacher` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`teacher` (
  `tid` INT NOT NULL,
  `User_uid` INT NOT NULL,
  PRIMARY KEY (`tid`, `User_uid`),
  INDEX `fk_teacher_User1_idx` (`User_uid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`class`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`class` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`class` (
  `idclasses` INT NOT NULL,
  `tid_class` INT NOT NULL,
  `location` VARCHAR(255) NOT NULL,
  `className` VARCHAR(45) NOT NULL,
  `classTime` TIME NOT NULL,
  `dataarchived` DATETIME NULL DEFAULT NULL,
  `archived` BINARY(1) NOT NULL,
  PRIMARY KEY (`idclasses`, `tid_class`),
  INDEX `fk_classes_teacher1_idx` (`tid_class` ASC) VISIBLE,
  CONSTRAINT `fk_class_teacher1`
    FOREIGN KEY (`tid_class`)
    REFERENCES `attendencemadeeasy`.`teacher` (`tid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`student`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`student` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`student` (
  `sid` INT NOT NULL,
  `User_uid` INT NOT NULL,
  PRIMARY KEY (`sid`, `User_uid`),
  INDEX `fk_Student_User1_idx` (`User_uid` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`student_attended`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`student_attended` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`student_attended` (
  `idStudent` INT NOT NULL,
  `classes_id` INT NOT NULL,
  `tid_class` INT NOT NULL,
  `location` BINARY(1) NOT NULL,
  `time` TIME NOT NULL,
  `date` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`idStudent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`student_inclass`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`student_inclass` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`student_inclass` (
  `sid` INT NOT NULL,
  `classes_idclasses` INT NOT NULL,
  `classes_teacher_idteacher` INT NOT NULL,
  PRIMARY KEY (`sid`, `classes_idclasses`, `classes_teacher_idteacher`),
  INDEX `fk_Student_has_classes_classes1_idx` (`classes_idclasses` ASC, `classes_teacher_idteacher` ASC) VISIBLE,
  INDEX `fk_Student_has_classes_Student1_idx` (`sid` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_classes_student1`
    FOREIGN KEY (`sid`)
    REFERENCES `attendencemadeeasy`.`student` (`sid`),
  CONSTRAINT `fk_student_has_classes_student_attended1`
    FOREIGN KEY (`sid`)
    REFERENCES `attendencemadeeasy`.`student_attended` (`idStudent`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`student_has_classes`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`student_has_classes` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`student_has_classes` (
  `student_has_classes_sid` INT NOT NULL,
  `class_idclasses` INT NOT NULL,
  `class_tid_class` INT NOT NULL,
  PRIMARY KEY (`student_has_classes_sid`, `class_idclasses`, `class_tid_class`),
  INDEX `fk_student_has_classes_has_class_class1_idx` (`class_idclasses` ASC, `class_tid_class` ASC) VISIBLE,
  INDEX `fk_student_has_classes_has_class_student_has_classes1_idx` (`student_has_classes_sid` ASC) VISIBLE,
  CONSTRAINT `fk_student_has_classes_has_class_class1`
    FOREIGN KEY (`class_idclasses` , `class_tid_class`)
    REFERENCES `attendencemadeeasy`.`class` (`idclasses` , `tid_class`),
  CONSTRAINT `fk_student_has_classes_has_class_student_has_classes1`
    FOREIGN KEY (`student_has_classes_sid`)
    REFERENCES `attendencemadeeasy`.`student_inclass` (`sid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `attendencemadeeasy`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `attendencemadeeasy`.`user` ;

CREATE TABLE IF NOT EXISTS `attendencemadeeasy`.`user` (
  `uid` INT NOT NULL,
  `fname` VARCHAR(45) NULL DEFAULT NULL,
  `lname` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(255) NOT NULL,
  `role` INT(1) UNSIGNED ZEROFILL NOT NULL,
  `password` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`uid`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  UNIQUE INDEX `uid_UNIQUE` (`uid` ASC) VISIBLE,
  CONSTRAINT `fk_user_student`
    FOREIGN KEY (`uid`)
    REFERENCES `attendencemadeeasy`.`student` (`User_uid`),
  CONSTRAINT `fk_user_teacher1`
    FOREIGN KEY (`uid`)
    REFERENCES `attendencemadeeasy`.`teacher` (`User_uid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
